### ISSUE TITLE
The program always executes first entered command 

### ISSUE THREAD

**Issue by sleshJdev** [CARICOM12/OOP#1]
Step to reproduce:
1. Run the program
2. Enter the command(for example _1. Add User_
_Enter all required information_
3. Enter the second command
Actual result: the first command will be performed 
Expected result: the second command should be performed

**Comment by CARICOM12** [comment]
The issue was fixed in this [commit](https://github.com/CARICOM12/OOP/commit/8ba9dcacc9a0d61ede86130d0ab0330674e21a19)
